# You can use this file to create a conda environment for this pipeline:
#   conda env create -f environment.yml
name: dolphinnext-rnaseq-3.0
channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - r-base=4.0.0
  - fastqc=0.11.8
  - star=2.6.1d # don't upgrade me - 2.7X indices incompatible with iGenomes.
  - hisat2=2.1.0
  - picard=2.18.27
  - rseqc=2.6.2
  - samtools=1.3
  - subread=1.6.4
  - tophat=2.1.1
  - trimmomatic=0.39
  - fastx_toolkit=0.0.14
  - bioconda::kallisto=0.46.0
  - ucsc-wigToBigWig=377
