install.packages("BiocManager", repos='http://cran.us.r-project.org')
install.packages("rmarkdown", repos='http://cran.us.r-project.org')
install.packages("devtools", repos='http://cran.us.r-project.org')
library(BiocManager)
install('tidyverse', ask = FALSE)
install("dplyr", ask = FALSE)
install('GenomicAlignments', ask = FALSE)
install('GenomicFeatures', ask = FALSE)
devtools::install_github("mojaveazure/seurat-disk", upgrade = "always")
