install.packages("BiocManager", repos='http://cran.us.r-project.org')
library(BiocManager)
install('GenomicAlignments', ask = FALSE)
install('GenomicFeatures', ask = FALSE)
install('anndata', ask = FALSE)
install.packages("Seurat")
