install.packages("BiocManager", repos='http://cran.us.r-project.org')
install.packages("rmarkdown", repos='http://cran.us.r-project.org')
install.packages("devtools", repos='http://cran.us.r-project.org')
library(BiocManager)
install("curl")
install("httr")
install('Seurat')
install('SingleCellExperiment')
install('xml2')
install('tidyverse')
install("dplyr")
install('Matrix')
install('scales')
install('RCurl')
install('svglite')
install('GenomicAlignments')
install('GenomicFeatures')
devtools::install_github("mojaveazure/seurat-disk", upgrade = "always")
